FROM alpine-jdk:base
MAINTAINER javaonfly
RUN apk --no-cache add netcat-openbsd
COPY ./event_management-0.0.1-SNAPSHOT.jar /opt/lib/
COPY ./Event-entrypoint.sh /opt/bin/Event-entrypoint.sh
RUN chmod 755 /opt/bin/Event-entrypoint.sh
ENTRYPOINT ["/usr/bin/java"]
CMD ["-jar", "/opt/lib/event_management-0.0.1-SNAPSHOT.jar"]
EXPOSE 8092
