FROM alpine-jdk:base
VOLUME /tmp
MAINTAINER javaonfly
RUN apk --no-cache add netcat-openbsd
COPY interaction.jar /var/lib/docker/
ENTRYPOINT ["java"]
CMD ["-jar", "/var/lib/docker/interaction.jar"]
EXPOSE 8181