version: '2.2'
services:
    eureka-server:
        container_name: eureka-server
        build:
            context: .
            dockerfile: Dockerfile-EurekaServer
        image: eureka-server:latest
        expose:
            - 8761
        ports:
            - 8761:8761
        networks:
            - emp-network
    PlaceService:
        container_name: Place
        build:
            context: .
            dockerfile: Dockerfile-Place
        image: place:latest
        expose:
            - 8099
        ports:
            - 8099:8099
        networks:
            - emp-network
        links:
            - eureka-server:eureka-server
        depends_on:
            - eureka-server
            - mysql-place-service
        logging:
            driver: json-file
        environment:
            - DATABASE_HOST=mysql-place-service
            - DATABASE_USER=user
            - DATABASE_PASSWORD=user
            - DATABASE_NAME=place_management
            - DATABASE_PORT=3306
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-place-service:3306/place_management
            - SPRING_APPLICATION_NAME=place-management
            - SPRING_PROFILES_ACTIVE=enableEureka
            - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
            - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-service:8761/eureka
    EventService:
        container_name: Event
        build:
            context: .
            dockerfile: Dockerfile-Event
        image: event:latest
        expose:
            - 8092
        ports:
            - 8092:8092
        networks:
            - emp-network
        links:
            - eureka-server:eureka-server
        depends_on:
            - eureka-server
            - mysql-event-service
        logging:
            driver: json-file
        environment:
            - DATABASE_HOST=mysql-event-service
            - DATABASE_USER=user
            - DATABASE_PASSWORD=user
            - DATABASE_NAME=event_management
            - DATABASE_PORT=3306
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-event-service:3306/event_management
            - SPRING_APPLICATION_NAME=event-management
            - SPRING_PROFILES_ACTIVE=enableEureka
            - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
            - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-service:8761/eureka
    UserService:
        container_name: User
        build:
            context: .
            dockerfile: Dockerfile-User
        image: user:latest
        expose:
            - 8070
        ports:
            - 8070:8070
        networks:
            - emp-network
        links:
            - eureka-server:eureka-server
        depends_on:
            - eureka-server
            - rabbitmq-service
            - mysql-user-service
        logging:
            driver: json-file
        environment:
            - DATABASE_HOST=mysql-user-service
            - DATABASE_USER=user
            - DATABASE_PASSWORD=user
            - DATABASE_NAME=user_management
            - DATABASE_PORT=3306
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-user-service:3306/user_management
            - SPRING_APPLICATION_NAME=user-management
            - SPRING_PROFILES_ACTIVE=enableEureka
            - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
            - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-service:8761/eureka
            - SPRING_RABBITMQ_HOST=rabbitmq-service
    InteractionService:
        container_name: Interaction
        build:
            context: .
            dockerfile: Dockerfile-Interaction
        image: interaction:latest
        expose:
            - 8181
        ports:
            - 8181:8181
        networks:
            - emp-network
        links:
            - eureka-server:eureka-server
        depends_on:
            - eureka-server
            - rabbitmq-service
            - mysql-interaction-service
        logging:
            driver: json-file
        environment:
            - DATABASE_HOST=mysql-interaction-service
            - DATABASE_USER=user
            - DATABASE_PASSWORD=user
            - DATABASE_NAME=interaction_management
            - DATABASE_PORT=3306
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-interaction-service:3306/interaction_management
            - SPRING_APPLICATION_NAME=interaction-management
            - SPRING_PROFILES_ACTIVE=enableEureka
            - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
            - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-service:8761/eureka
            - SPRING_RABBITMQ_HOST=rabbitmq-service
    GatewayService:
        container_name: Gateway
        build:
            context: .
            dockerfile: Dockerfile-Gateway
        image: gateway:latest
        expose:
            - 8080
        ports:
            - 8080:8080
        networks:
            - emp-network
        links:
            - eureka-server:eureka-server
        depends_on:
            - eureka-server
        logging:
            driver: json-file
        environment:
            - SPRING_APPLICATION_NAME=gateway
            - SPRING_PROFILES_ACTIVE=enableEureka
            - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
            - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-service:8761/eureka
    rabbitmq-service:
      image: rabbitmq:3-management
      hostname: rabbitmq
      environment:
      - RABBITMQ_DEFAULT_USER= guest
      - RABBITMQ_DEFAULT_PASS= guest
      ports:
      - "5672:5672"
      networks:
      - emp-network
    mysql-interaction-service:
        image: mysql:5.7.22
        container_name: mysql-interaction-service
        ports:
            - 3306:3306
        networks: 
            - emp-network
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=interaction_management
            - MYSQL_USER=user
            - MYSQL_PASSWORD=user
    mysql-user-service:
        image: mysql:5.7.22
        container_name: mysql-user-service
        ports:
            - 3307:3306
        networks:
            - emp-network
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=user_management
            - MYSQL_USER=user
            - MYSQL_PASSWORD=user
    mysql-event-service:
        image: mysql:5.7.22
        container_name: mysql-event-service
        ports:
            - 3308:3306
        networks: 
            - emp-network
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=event_management
            - MYSQL_USER=user
            - MYSQL_PASSWORD=user
    mysql-place-service:
        image: mysql:5.7.22
        container_name: mysql-place-service
        ports:
            - 3309:3306
        networks: 
            - emp-network
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=place_management
            - MYSQL_USER=user
            - MYSQL_PASSWORD=user
networks:
    emp-network:
        driver: bridge
volumes:
    tmp:
        external: false