version: '3'

services:
    rabbitmq:
        build:
            context: .
            dockerfile: Dockerfile-Rabbitmq
        image: rabbitmq:3.7.4-management
        hostname: rabbitmq
        ports:
            - "5672:5672"
            - "15672:15672"
        environment:
            RABBITMQ_DEFAULT_USER: guest
            RABBITMQ_DEFAULT_PASS: guest
        networks:
            - mreza

    eurekaserver:
        build:
            context: .
            dockerfile: Dockerfile-EurekaServer
        image: eurekaserver:latest
        ports: 
            - 8761:8761
        networks:
            - mreza

    EventService:
        build:
            context: .
            dockerfile: Dockerfile-Event
        image: event:latest
        depends_on:
            - mysql-event
            - eurekaserver
        ports:
            - 8092:8092
        environment:
            SPRING_DATASOURCE_URL: 'jdbc:mysql://mysql-event:3306/event_management'
            SPRING_APPLICATION_NAME: event-management
            SPRING_PROFILES_ACTIVE: enableEureka
            EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
            EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8761/eureka/
        networks:
            - mreza

    PlaceService:
        build:
            context: .
            dockerfile: Dockerfile-Place
        image: place:latest
        depends_on:
            - mysql-place
            - eurekaserver
        ports:
            - 8099:8099
        environment:
            SPRING_DATASOURCE_URL: 'jdbc:mysql://mysql-place:3306/place_management'
            SPRING_APPLICATION_NAME: place-management
            SPRING_PROFILES_ACTIVE: enableEureka
            EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
            EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8761/eureka/
        networks:
            - mreza

    InteractionService:
        build:
            context: .
            dockerfile: Dockerfile-Interaction
        image: interaction:latest
        depends_on:
            - mysql-interaction
            - eurekaserver
            - rabbitmq
        ports:
            - 8181:8181
        environment:
            SPRING_RABBITMQ_HOST: rabbitmq
            SPRING_DATASOURCE_URL: 'jdbc:mysql://mysql-interaction:3306/interaction_management'
            SPRING_APPLICATION_NAME: interaction-management
            SPRING_PROFILES_ACTIVE: enableEureka
            EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
            EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8761/eureka/
        networks:
            - mreza

    UserService:
        build:
            context: .
            dockerfile: Dockerfile-User
        image: user:latest
        depends_on:
            - mysql-user
            - eurekaserver
            - rabbitmq
        ports:
            - 8070:8070
        environment:
            SPRING_RABBITMQ_HOST: rabbitmq
            SPRING_DATASOURCE_URL: 'jdbc:mysql://mysql-user:3306/user_management'
            SPRING_APPLICATION_NAME: user-management
            SPRING_PROFILES_ACTIVE: enableEureka
            EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
            EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8761/eureka/
        networks:
            - mreza

    Gateway:
        build:
            context: .
            dockerfile: Dockerfile-Gateway
        image: gateway:latest
        depends_on:
            - eurekaserver
        ports:
            - 8080:8080
        environment:
            SPRING_APPLICATION_NAME: gateway
            SPRING_PROFILES_ACTIVE: enableEureka
            EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
            EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8761/eureka/
        networks:
            - mreza

    mysql-place:
        build:
            context: .
            dockerfile: Dockerfile-Mysql
        image: mysqlimg:latest
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=place_management
        networks: 
            - mreza

    mysql-event:
        build:
            context: .
            dockerfile: Dockerfile-Mysql
        image: mysqlimg:latest
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=event_management
        networks: 
            - mreza

    mysql-interaction:
        build:
            context: .
            dockerfile: Dockerfile-Mysql
        image: mysqlimg:latest
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=interaction_management
        networks: 
            - mreza

    mysql-user:
        build:
            context: .
            dockerfile: Dockerfile-Mysql
        image: mysqlimg:latest
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=user_management
        networks: 
            - mreza

networks:
    mreza:
        driver: bridge
