FROM alpine-jdk:base
MAINTAINER javaonfly
RUN apk --no-cache add netcat-openbsd
COPY ./interaction_management.jar /opt/lib/
COPY ./Interaction-entrypoint.sh /opt/bin/Interaction-entrypoint.sh
RUN chmod 755 /opt/bin/Interaction-entrypoint.sh
ENTRYPOINT ["/usr/bin/java"]
CMD ["-jar", "/opt/lib/interaction_management.jar"]
EXPOSE 8181