FROM alpine-jdk:base
MAINTAINER javaonfly
RUN apk --no-cache add netcat-openbsd
COPY ./place_management-0.0.1-SNAPSHOT.jar /opt/lib/
COPY ./Place-entrypoint.sh /opt/bin/Place-entrypoint.sh
RUN chmod 755 /opt/bin/Place-entrypoint.sh
ENTRYPOINT ["/usr/bin/java"]
CMD ["-jar", "/opt/lib/place_management-0.0.1-SNAPSHOT.jar"]
EXPOSE 8099
