FROM alpine-jdk:base
MAINTAINER javaonfly
RUN apk --no-cache add netcat-openbsd
COPY ./ms.jar /opt/lib/
COPY ./User-entrypoint.sh /opt/bin/User-entrypoint.sh
RUN chmod 755 /opt/bin/User-entrypoint.sh
ENTRYPOINT ["/usr/bin/java"]
CMD ["-jar", "/opt/lib/ms.jar"]
EXPOSE 8070