FROM alpine-jdk:base
MAINTAINER javaonfly
COPY ./Gateway.jar /opt/lib/
COPY ./Gateway-entrypoint.sh /opt/bin/Gateway-entrypoint.sh
RUN chmod 755 /opt/bin/Gateway-entrypoint.sh
ENTRYPOINT ["/usr/bin/java"]
CMD ["-jar", "/opt/lib/Gateway.jar"]
EXPOSE 8080