FROM alpine-jdk:base
MAINTAINER javaonfly
RUN apk --no-cache add netcat-openbsd
COPY ./ms-0.0.1-SNAPSHOT.jar /opt/lib/
COPY ./User-entrypoint.sh /opt/bin/User-entrypoint.sh
RUN chmod 755 /opt/bin/User-entrypoint.sh
ENTRYPOINT ["/usr/bin/java"]
CMD ["-jar", "/opt/lib/ms-0.0.1-SNAPSHOT.jar"]
EXPOSE 8070
